# Generated by Django 4.2.3 on 2023-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
