# Generated by Django 4.2.3 on 2023-09-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='academicprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='country',
        ),
    ]
