# Generated by Django 4.2.3 on 2023-09-20 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_academicprofile_county_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('ADMINISTRATOR', 'Admin'), ('Guardian', 'Guardian')], default='Student', max_length=15),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
