# Generated by Django 4.2.3 on 2023-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0005_topicalquizes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicalquizes',
            name='file',
            field=models.FileField(null=True, upload_to='question_files/'),
        ),
    ]
