# Generated by Django 4.2.3 on 2023-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_studentknecexams_exam_type_studenttest_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltest',
            name='exam_type',
            field=models.CharField(choices=[('Topical', 'Topical'), ('General', 'General'), ('Retake', 'Retake'), ('KNEC', 'KNEC')], default='Topical', max_length=10),
        ),
    ]
