# Generated by Django 4.2.3 on 2023-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='test_size',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='time',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
