# Generated by Django 4.2.3 on 2023-09-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0003_remove_progress_subtopic_progress_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinquiries',
            name='quiz_class',
        ),
        migrations.DeleteModel(
            name='AcademicInquiries',
        ),
    ]
